### ISSUE TITLE
Experiment data

### ISSUE THREAD

**Issue by edgar-explorer** [jhultman/dead-reckoning#1]
Hi, may you provide magnetometer and GPS data? Thank you, sincerely.

**Comment by balamuruganky** [comment]
@jhultman : Thanks for the great algorithm. It would be appriciated, if you could share the input CSV files. Thanks in advance.

**Comment by jhultman** [comment]
Hi, I have looked for this data but cannot find it at the moment. I will share it if I can find it. Sorry for the trouble.

**Comment by balamuruganky** [comment]
@jhultman : Thanks for considering my request.

**Comment by jhultman** [comment]
Hi @cumtchenchang and @balamuruganky, I have now uploaded the data to this repo. Thank you for your patience.

**Comment by balamuruganky** [comment]
@jhultman : Thanks much for sharing the CSV files. Much appriciated!!!
